# Copyright (c) 2026 Prajnaana Technologies Pvt. Ltd.
# Original author: Dhanya Shree S
# SPDX-License-Identifier: MIT
#
# Licensed under the MIT License. See LICENSE in the project root.

"""run_pipeline, for real: the only fake is the board.

tests/test_governance.py::_pipeline_harness drives run_pipeline with
generate_tests, govern, run_suite and the KPI store all replaced by fakes.
That proves the orchestration bookkeeping -- who is called, in what order,
with what -- and nothing at all about the path a run takes on the bench:
no module is written, nothing is compiled, no assertion is executed, and
the verdict the pipeline reports is a string the harness handed it.

Here everything is the product's own code:

  * generate_tests writes the planner-selected module, for real, and
    build_canonical_suite turns a requirement document into the second
    module through canonical.build and generate_from_canonical.generate.
  * govern runs the real acceptance rules over the real generated bytes.
  * run_suite really invokes pytest on both files, and the verdict comes
    back from what pytest reported.
  * kpi.record_run really writes the history entry.

The only fake is the board, because there is none: FakeBLEDevice stands in
for RealBLEDevice. It answers the same calls, returns plausible telemetry,
and echoes audio back through a compressor-shaped gain, so the
hardware-touching tests in the generated modules either pass against it or
skip with a reason -- which is what they would do on the bench.

Two settings are forced rather than faked: the planner runs in rules mode
(HA_AI=rules), so no model is called and no key is needed, and
HA_TEST_SECONDS is an eighth of a second, which is one burst.

Everything written goes under tmp_path: the writable root, the log
directory, both generated modules and the approvals store are all
redirected, so a run here leaves nothing behind and reads nothing a
previous run left.
"""

import ast
import asyncio
import os
import sys
import time

import numpy as np
import pytest

from regression import governance, kpi, measurements, paths, reporting
from regression.ai_engine import canonical, generate_from_canonical, planner
from regression.ai_engine import generate_tests as generate_tests_module
from regression.ai_engine import orchestrator
from regression.ble import ble_audio


# --------------------------------------------------------------------------
# The board, and only the board
# --------------------------------------------------------------------------

# One service holding the two characteristics ble_audio names. Firmware
# that does not implement the loopback is firmware that does not publish
# the processed-audio notify characteristic, so that is how "no loopback"
# is modelled: the characteristic is absent from the table, which is what
# tools/ble_probe.py would report of such a board.
FAKE_SERVICE_UUID = "12345678-1234-5678-1234-56789abcdef0"

# The capability probe as the product defines it, bound now: the staged
# fixture replaces ble_audio.RealBLEDevice with a factory for the fake, so
# reading the attribute later would find the stand-in and prove nothing.
_REAL_LOOPBACK_PROBE = ble_audio.RealBLEDevice.supports_audio_loopback
_REAL_LOOPBACK_CHARACTERISTIC = ble_audio.RealBLEDevice.loopback_characteristic


class _FakeCharacteristic:

    def __init__(self, uuid, properties):
        self.uuid = uuid
        self.properties = properties


class _FakeService:

    def __init__(self, uuid, characteristics):
        self.uuid = uuid
        self.characteristics = characteristics


class _FakeGATTTable:
    """The part of bleak's BleakGATTServiceCollection the probe reads."""

    def __init__(self, device):
        self._device = device

    def _characteristics(self):
        characteristics = [
            _FakeCharacteristic(ble_audio.WRITE_CHAR_UUID,
                                ["write-without-response"]),
        ]

        if self._device.loopback:
            characteristics.append(_FakeCharacteristic(
                ble_audio.NOTIFY_CHAR_UUID,
                getattr(self._device, "notify_properties", ["notify"])))

        return characteristics

    def get_characteristic(self, specifier):
        wanted = str(specifier).lower()

        for characteristic in self._characteristics():
            if characteristic.uuid.lower() == wanted:
                return characteristic

        return None

    def __iter__(self):
        return iter([_FakeService(FAKE_SERVICE_UUID, self._characteristics())])


class _FakeClient:
    """The bleak client surface ble_audio reaches through itself.

    The capability probe is the only thing that uses it: every other call
    the generated modules make is answered by FakeBLEDevice directly. So
    "writes" counts exactly what the probe wrote to the board, and
    "table_reads" what it read from the GATT table -- which is how the
    tests below can say what the capability was decided from.
    """

    def __init__(self, device):
        self._device = device
        self.mtu_size = 247
        self.writes = 0
        self.table_reads = 0

        # bleak raises when the table cannot be read on this link -- the
        # link dropped, or discovery has not finished. Unknown, which is
        # not the same answer as "this firmware has no loopback".
        self.table_error = False

    @property
    def is_connected(self):
        return self._device.connected

    @property
    def services(self):
        if self.table_error or not self._device.connected:
            raise RuntimeError("Service Discovery has not been performed yet")

        self.table_reads += 1

        return _FakeGATTTable(self._device)

    async def write_gatt_char(self, uuid, data, response=False):
        self.writes += 1

        if self._device.probe_write_error:
            raise RuntimeError("Unreachable: the write was not acknowledged")

        # The echo a working loopback sends back arrives as notifications,
        # whatever wrote the audio.
        if self._device.loopback and self._device.dsp != "silent":
            self._device.processed_audio.extend(bytes(data))


class _StubBleakClient:
    """The bleak surface RealBLEDevice.connect itself reaches for.

    FakeBLEDevice replaces the whole device; this replaces only the client
    underneath a real RealBLEDevice, which is the only way to exercise
    connect().
    """

    def __init__(self, loopback):
        self.loopback = loopback
        self.is_connected = False
        self.notify_failures = 0
        self.mtu_size = 247

    async def connect(self, timeout=None):
        self.is_connected = True

    @property
    def services(self):
        return _FakeGATTTable(self)

    async def start_notify(self, uuid, handler):
        if self.services.get_characteristic(uuid) is None:
            self.notify_failures += 1

            raise RuntimeError(
                "Characteristic {} was not found!".format(uuid))


class _Unpaced:
    """asyncio with the waits taken out.

    connect() sleeps two seconds for the link to stabilise and backs off
    between attempts. Against a stub there is nothing to wait for, and the
    suite should not pay for it.
    """

    def __getattr__(self, name):
        return getattr(asyncio, name)

    async def sleep(self, seconds, *args, **kwargs):
        return await asyncio.sleep(0)


class FakeBLEDevice:
    """A stand-in for RealBLEDevice with no radio behind it.

    It implements the surface the generated modules and
    regression/measurements.py actually call. Three behaviours matter:

    loopback -- whether this firmware implements the loopback at all,
        which means whether NOTIFY_CHAR_UUID is in the GATT table above.
        False is the honest answer for firmware without the echo, and
        makes every audio test skip rather than fail, exactly as
        require_loopback intends.

    dsp -- what the echo does to the audio. "compressor" applies less gain
        to loud input than to quiet input, which is what a hearing aid
        does and what test_compression_curve checks for. "passthrough"
        returns the input untouched: a device whose DSP has stopped
        working, which the suite is supposed to catch. "silent" notifies
        nothing back although the firmware publishes the characteristic,
        which is what the board does when the DSP hangs, a write fails or
        the reply times out -- the difference between that and
        loopback=False is a failure against a skip, so the two are
        separate settings.

    probe_write_error -- the capability probe's own GATT writes raise. The
        probe runs first thing after connect, so a link still settling
        rejects them while audio streamed a moment later gets through.
        Nothing else in this stand-in writes at that layer.
    """

    # The firmware clamps its WDRC gain to roughly this range; these two
    # sit inside the generated suite's GAIN_MIN/GAIN_MAX window and are far
    # enough apart to satisfy MIN_COMPRESSION_RATIO.
    QUIET_GAIN = 0.85
    LOUD_GAIN = 0.55

    # Full-scale fraction above which the input counts as loud.
    LOUD_RMS = 0.2

    BUILD_ID = "fake-board+0badc0de"

    def __init__(self, loopback=True, dsp="compressor"):
        self.loopback = loopback
        self.dsp = dsp
        self.probe_write_error = False
        self.connected = False
        self.connects = 0
        self.streams = 0
        self.bonded = False
        self._latency_ms = None
        self._battery = 96

        # What RealBLEDevice's capability probe works with, so that the
        # probe exercised here is the product's own rather than a summary
        # of what it is believed to do.
        self.client = _FakeClient(self)
        self.processed_audio = bytearray()
        self._loopback = None

    # ---------------- link ----------------
    @property
    def is_connected(self):
        return self.connected

    async def connect(self):
        self.connects += 1
        self.connected = True

    async def disconnect(self):
        self.connected = False

    def reset_link_counters(self):
        pass

    # ---------------- transfer ----------------
    async def write(self, data):
        if not self.connected:
            await self.connect()

        return len(data)

    def _processed(self, samples):
        if self.dsp == "passthrough":
            return samples

        level = float(np.sqrt(np.mean(np.square(
            samples.astype(np.float64))))) / 32767.0
        gain = self.LOUD_GAIN if level > self.LOUD_RMS else self.QUIET_GAIN

        return np.round(samples.astype(np.float64) * gain).astype(np.int16)

    async def send_audio_stream(self, audio_data, params=None):
        """Echo one burst back, the way the firmware's loopback does.

        Mirrors RealBLEDevice: a float array is scaled to PCM16 first, and
        a burst is capped at MAX_BURST_BYTES, because the device's return
        buffer is that size.
        """
        if not self.connected:
            await self.connect()

        started = time.monotonic()

        if isinstance(audio_data, np.ndarray):
            data = (audio_data.flatten() * 32767).astype(np.int16).tobytes()
        else:
            data = bytes(audio_data)

        data = data[:ble_audio.MAX_BURST_BYTES]
        self.streams += 1

        if not self.loopback or self.dsp == "silent":
            self._latency_ms = None

            return None

        # Let the loop turn, as a real notification would.
        await asyncio.sleep(0)

        samples = np.frombuffer(data, dtype=np.int16)
        self._latency_ms = (time.monotonic() - started) * 1000.0

        return self._processed(samples).tobytes()

    @property
    def last_stream_latency_ms(self):
        return self._latency_ms

    # The product's own probe, run against the fake GATT table above
    # rather than reimplemented here. A fake that answered self.loopback
    # directly cannot see a defect in the probe.
    def loopback_characteristic(self):
        return _REAL_LOOPBACK_CHARACTERISTIC(self)

    async def supports_audio_loopback(self, force=False):
        return await _REAL_LOOPBACK_PROBE(self, force)

    # ---------------- readings ----------------
    async def read_battery(self):
        # Drains a little across a run, so battery_drain is a real number.
        level = self._battery
        self._battery = max(0, self._battery - 1)

        return level

    async def read_memory(self):
        return 0.52

    async def read_power(self):
        return None

    async def measure_sync_latency(self):
        return 11.0

    async def read_retry_count(self):
        return 0

    async def read_build_id(self):
        return self.BUILD_ID

    async def read_telemetry(self):
        return {"memory": 0.52, "sync": 11.0, "retry": 0,
                "battery": self._battery}

    async def read_metrics(self):
        return {"memory": 0.52, "sync": 11.0, "retry": 0,
                "battery": self._battery, "unmeasured": ["power"]}

    # ---------------- security ----------------
    async def pair(self):
        self.bonded = True

        return True

    async def unpair(self):
        self.bonded = False

        return True

    async def read_bond_count(self):
        return 1 if self.bonded else None

    async def is_encrypted(self):
        return self.bonded


# --------------------------------------------------------------------------
# Fixtures
# --------------------------------------------------------------------------

# Four requirements, chosen so the canonical suite that comes out of them
# has all three shapes in it: a measurement with limits read from the
# sentence (battery, and the signal-to-noise ratio), a case that drives the
# link directly (the 200-byte packet), and a case this bench cannot run at
# all (noise cancellation, which has no interface here). A run against the
# shipped REQUIREMENTS.md emits seventy cases; four requirements make the
# same code path finish in a fraction of a second.
SMALL_REQUIREMENTS = """# Requirements for the end-to-end test

- REQ-BAT-001: The battery level shall be between 0 and 100 percent.
- REQ-BLE-002: The device shall accept a 200 byte packet without dropping the link.
- REQ-ANC-003: Noise cancellation shall remain stable while the compressor is active.
- REQ-DSP-004: The signal-to-noise ratio of the processed audio shall be at least 5 dB.
"""

SMALL_RELEASE_NOTE = """# Release notes

## {build_id}

### Audio
- The compressor release constant was retuned.
"""

# Metrics a healthy board would report: every one inside
# risk_engine.METRIC_THRESHOLDS, so the generated metric tests pass and the
# planner is not reacting to a breach.
HEALTHY_METRICS = {
    "memory": 0.52,
    "sync": 11.0,
    "retry": 0,
    "battery": 96,
    "unmeasured": ["power"],
}


class _Staged:
    """What a staged run needs to talk about afterwards."""

    def __init__(self, root, planner_module, canonical_module, device):
        self.root = root
        self.planner_module = planner_module
        self.canonical_module = canonical_module
        self.device = device
        self.build_id_reads = []
        self.plans = []

    def source(self, path):
        with open(path, encoding="utf-8") as handle:
            return handle.read()

    def junit(self, run_dir):
        """The records pytest itself wrote, re-read from its XML."""
        return reporting.parse_junit(os.path.join(run_dir, "results.xml"))


def _reset_event_loop():
    policy = asyncio.get_event_loop_policy()

    try:
        loop = policy.get_event_loop()
    except RuntimeError:
        loop = None

    if loop is None or loop.is_closed():
        policy.set_event_loop(policy.new_event_loop())


@pytest.fixture
def staged(tmp_path, monkeypatch):
    """Point every path the pipeline writes to at tmp_path, and fake the board.

    Everything redirected here was resolved once at import time and copied
    into several modules by value, so each holder is set individually --
    patching regression.paths alone would leave the orchestrator writing
    into the checkout.
    """
    generated = tmp_path / "generated"
    generated.mkdir()

    planner_module = generated / "test_ai_generated.py"
    canonical_module = generated / "test_from_canonical.py"
    logs = tmp_path / "logs"

    # The writable root: kpi's history and governance's approvals store both
    # resolve through paths.in_base, which reads this at call time.
    monkeypatch.setattr(paths, "BASE_DIR", str(tmp_path))
    monkeypatch.setattr(paths, "LOGS_DIR", str(logs))
    monkeypatch.setattr(paths, "GENERATED_TEST_PATH", str(planner_module))
    monkeypatch.setattr(paths, "CANONICAL_TEST_PATH", str(canonical_module))

    # The copies taken at import.
    monkeypatch.setattr(generate_tests_module, "GENERATED_TEST_PATH",
                        str(planner_module))
    monkeypatch.setattr(generate_from_canonical, "CANONICAL_TEST_PATH",
                        str(canonical_module))
    monkeypatch.setattr(orchestrator, "GENERATED_TEST_PATH",
                        str(planner_module))
    monkeypatch.setattr(orchestrator, "CANONICAL_TEST_PATH",
                        str(canonical_module))
    monkeypatch.setattr(governance, "GENERATED_TEST_PATH", str(planner_module))
    monkeypatch.setattr(governance, "CANONICAL_TEST_PATH",
                        str(canonical_module))

    device = FakeBLEDevice()

    # Every construction site of the board, in the modules that hold a
    # reference to the class. The conftest.py that generate_tests copies
    # next to the generated modules is imported fresh by the inner pytest
    # run and reads ble_audio.RealBLEDevice then, so patching it there is
    # what puts the fake behind the ble_device fixture.
    monkeypatch.setattr(ble_audio, "RealBLEDevice", lambda: device)
    monkeypatch.setattr(orchestrator, "RealBLEDevice", lambda: device)

    requirements = tmp_path / "REQUIREMENTS.md"
    requirements.write_text(SMALL_REQUIREMENTS, encoding="utf-8")

    note = tmp_path / "RELEASE_NOTES.md"
    note.write_text(
        SMALL_RELEASE_NOTE.format(build_id=FakeBLEDevice.BUILD_ID),
        encoding="utf-8")

    monkeypatch.setenv(orchestrator.REQUIREMENTS_ENV, str(requirements))
    monkeypatch.setenv(orchestrator.RELEASE_NOTE_ENV, str(note))
    monkeypatch.setenv("HA_AI", "rules")

    # The audio tests read the whole stimulus otherwise; an eighth of a
    # second is one burst, which is all the fake echoes in one call.
    monkeypatch.setenv("HA_TEST_SECONDS", "0.125")

    # run_pipeline asks the board for the build id when HA_BUILD_ID is
    # unset, which is the path worth exercising: it must ask exactly once.
    monkeypatch.delenv(orchestrator.BUILD_ID_ENV, raising=False)

    state = _Staged(tmp_path, str(planner_module), str(canonical_module),
                    device)

    real_read_build_id = orchestrator.read_build_id

    def counted_read_build_id():
        value = real_read_build_id()
        state.build_id_reads.append(value)

        return value

    monkeypatch.setattr(orchestrator, "read_build_id", counted_read_build_id)

    # The real generator, with a note taken of every plan it returns. The
    # escalation is the only thing that calls it twice, and the second plan
    # has to be harder than the first -- which is a fact about raise_to, not
    # about the planner making a different choice from the same evidence.
    real_generate_tests = orchestrator.generate_tests

    def recorded_generate_tests(*args, **kwargs):
        plan = real_generate_tests(*args, **kwargs)
        state.plans.append(plan)

        return plan

    monkeypatch.setattr(orchestrator, "generate_tests",
                        recorded_generate_tests)

    # Globals the inner pytest run moves and does not put back.
    saved_path = list(sys.path)
    saved_modules = set(sys.modules)

    yield state

    for name in sorted(set(sys.modules) - saved_modules):
        module = sys.modules.get(name)
        origin = getattr(module, "__file__", None) or ""

        if origin.startswith(str(tmp_path)):
            del sys.modules[name]

    sys.path[:] = saved_path

    # The generated_tests conftest closes the loop it made; leaving a closed
    # loop installed breaks anything later in this session that asks for one.
    _reset_event_loop()


def _compiles(path, source):
    """Compile the generated bytes. Raises SyntaxError if they do not."""
    compile(source, path, "exec")

    return True


def _test_names(source):
    """The test functions a generated module defines."""
    return sorted(
        node.name for node in ast.walk(ast.parse(source))
        if isinstance(node, ast.FunctionDef) and node.name.startswith("test_")
    )


# The measurements that send PCM and read back what the DSP returned, so
# none of them has an answer on a board with no loopback. The other three --
# battery, stack and build_id -- are characteristic reads.
AUDIO_MEASUREMENTS = ("snr", "latency", "compression", "gain_range",
                      "sign_flips", "compressor_timing")


def _tests_needing_audio(source):
    """Every test in a generated module that needs audio to come back.

    Two shapes need it: a test that streams audio, which both generators
    guard with require_loopback, and a test that measures one of
    AUDIO_MEASUREMENTS. Read out of the module rather than listed by name,
    so the assertion below covers whatever the generators emitted and not a
    list that goes stale the next time a scenario is added.
    """
    needed = set()

    for node in ast.walk(ast.parse(source)):
        if not (isinstance(node, ast.FunctionDef)
                and node.name.startswith("test_")):
            continue

        for call in ast.walk(node):
            if not isinstance(call, ast.Call):
                continue

            name = getattr(call.func, "id", None) \
                or getattr(call.func, "attr", None)

            if name == "require_loopback":
                needed.add(node.name)
            elif name == "take" and any(
                    isinstance(argument, ast.Constant)
                    and argument.value in AUDIO_MEASUREMENTS
                    for argument in call.args):
                needed.add(node.name)

    return needed


# --------------------------------------------------------------------------
# The whole pipeline, with a healthy board
# --------------------------------------------------------------------------

def test_the_real_pipeline_generates_governs_and_runs_both_modules(staged):
    """One run, end to end, with nothing between the steps replaced."""
    started = time.monotonic()

    result = orchestrator.run_pipeline(
        metrics=dict(HEALTHY_METRICS, unmeasured=["power"]),
        change_info="the compressor release constant was retuned",
    )

    elapsed = time.monotonic() - started

    # ---- the modules exist, and are real Python ----
    for path in (staged.planner_module, staged.canonical_module):
        assert os.path.exists(path), "the pipeline did not write " + path

        source = staged.source(path)

        assert _compiles(path, source), path
        assert _test_names(source), "{} defines no tests".format(path)

    planner_source = staged.source(staged.planner_module)
    canonical_source = staged.source(staged.canonical_module)

    # The canonical module is the requirement document's, not a leftover.
    assert "REQ-BAT-001" in canonical_source
    assert "REQ-ANC-003" in canonical_source, (
        "a requirement this bench cannot run was dropped instead of skipped")

    # ---- governance saw those bytes, and passed them ----
    for path in (staged.planner_module, staged.canonical_module):
        assert governance.check_file(path) == [], (
            "{} breaks an acceptance rule".format(os.path.basename(path)))

    assert result["governance"] == "{}, {}".format(
        governance.REVIEWED, governance.REVIEWED), result["governance"]

    # ---- pytest really collected and ran them ----
    records = staged.junit(result["run_dir"])

    assert records, "pytest wrote no JUnit XML, so nothing ran"
    assert len(records) == len(result["tests"])

    ran = {record.name for record in records}
    generated = set(_test_names(planner_source)) | set(
        _test_names(canonical_source))

    assert ran == generated, (
        "pytest ran a different set of tests from the ones generated; "
        "missing {}, unexpected {}".format(
            sorted(generated - ran), sorted(ran - generated)))

    assert len(ran) > 10, "only {} tests were generated".format(len(ran))

    # Something was really executed, not merely collected and skipped.
    passed = [r for r in records if r.status == reporting.PASSED]

    assert len(passed) >= 5, [(r.name, r.status) for r in records]

    # The board-driven ones are among them: the fake answered, and the
    # generated code did the arithmetic that judges the answer.
    assert "test_connection" in {r.name for r in passed}
    assert "test_compression_curve" in {r.name for r in passed}, (
        "the compressor test did not pass against a compressing device")

    # Nothing failed, and every skip says why.
    failures = [r for r in records if r.status in
                (reporting.FAILED, reporting.ERROR)]

    assert not failures, [(r.name, r.message) for r in failures]

    for record in records:
        if record.status == reporting.SKIPPED:
            assert record.message.strip(), (
                "{} skipped without saying why".format(record.name))

    # ---- the verdict is pytest's verdict ----
    assert result["status"] == "pass"
    assert result["status"] == reporting.RunReport(
        run_dir=result["run_dir"], records=records).status

    # A passing run plans once; nothing escalates.
    assert len(staged.plans) == 1, "a passing run re-planned"
    assert staged.plans[0].intensity == result["intensity"]

    # ---- the KPI records what pytest reported ----
    runs = kpi.load_runs()

    assert len(runs) == 1, "the run was not recorded once"

    entry = runs[0]

    assert entry["status"] == result["status"]
    assert entry["passed"] == len(passed)
    assert entry["failed"] == 0
    assert entry["skipped"] == sum(
        1 for r in records if r.status == reporting.SKIPPED)
    assert entry["verdicts"] == {r.name: r.status for r in records}
    assert entry["intensity"] == result["intensity"]
    assert entry["risk_score"] == result["risk_score"]

    # ---- the build id came from the board, once ----
    assert staged.build_id_reads == [FakeBLEDevice.BUILD_ID], (
        "the board was asked for its build id {} time(s)".format(
            len(staged.build_id_reads)))
    assert entry["build_id"] == FakeBLEDevice.BUILD_ID

    # ---- the run wrote its evidence where it said it did ----
    assert result["run_dir"].startswith(str(staged.root))
    assert os.path.exists(os.path.join(result["run_dir"], "summary.txt"))

    for record in records:
        log = os.path.join(result["run_dir"], "tests", record.name + ".log")

        assert os.path.exists(log), "no log file for " + record.name

    # ---- the battery drain came from the board ----
    assert result["battery_start"] == HEALTHY_METRICS["battery"]
    assert result["battery_drain"] is not None

    # A whole run, on a machine with no board and no network.
    assert elapsed < 60, "the pipeline took {:.1f}s".format(elapsed)


def test_a_board_without_loopback_makes_the_audio_tests_skip_not_fail(
        staged, monkeypatch):
    """Firmware with no audio echo is a gap, not a regression.

    require_loopback exists to say so. With the probe answering no, every
    audio test in the planner-selected module must skip with that reason
    and the run must still pass.

    Requirements and the release note are cleared, which is what the
    dashboard's Clear button sends, so this is also the one-module run:
    build_canonical_suite returns "" and govern reports a single state. The
    run with both modules is the test below.
    """
    staged.device.loopback = False

    monkeypatch.setenv(orchestrator.REQUIREMENTS_ENV, "")
    monkeypatch.setenv(orchestrator.RELEASE_NOTE_ENV, "")

    result = orchestrator.run_pipeline(
        metrics=dict(HEALTHY_METRICS, unmeasured=["power"]),
        change_info="documentation wording tidy-up",
    )

    assert not os.path.exists(staged.canonical_module), (
        "a requirement suite was written although there are no requirements")

    assert result["governance"] == governance.REVIEWED, result["governance"]

    records = {r.name: r for r in staged.junit(result["run_dir"])}

    assert records, "nothing ran"

    # Every audio test, not one of them.
    audio = _tests_needing_audio(staged.source(staged.planner_module))

    assert "test_audio_dsp" in audio, sorted(audio)
    assert len(audio) >= 7, "only {} audio tests: {}".format(
        len(audio), sorted(audio))

    for name in sorted(audio):
        record = records[name]

        assert record.status == reporting.SKIPPED, (name, record.message)
        assert "loopback" in (record.message + record.detail).lower(), (
            name, record.message)

    assert result["status"] == "pass", (
        "a missing feature was reported as a failing run")

    entry = kpi.load_runs()[0]

    assert entry["skipped"] >= len(audio), (
        "the audio tests alone account for {} skips".format(len(audio)))
    assert entry["failed"] == 0

    # The metric tests still ran: a board with no audio echo still reports
    # its telemetry, so the run is not empty.
    assert records["test_memory"].status == reporting.PASSED


def test_a_board_without_loopback_skips_in_both_generated_modules(staged):
    """The two modules must say the same thing about a missing feature.

    Both must skip. The planner-selected module skips all seven of its
    audio tests through require_loopback, and the requirement-driven module
    skips the cases derived from an audio requirement.

    The requirements are left in place here, which is the difference from
    the test above: both modules are written, and both have to agree.
    """
    # Held against measurements.MEASUREMENTS so that a measurement added
    # later has to be classified rather than quietly left out of this.
    assert set(AUDIO_MEASUREMENTS) | {"battery", "stack", "build_id"} == set(
        measurements.MEASUREMENTS)

    staged.device.loopback = False

    result = orchestrator.run_pipeline(
        metrics=dict(HEALTHY_METRICS, unmeasured=["power"]),
        change_info="the compressor release constant was retuned",
    )

    assert os.path.exists(staged.canonical_module), (
        "no requirement suite was written, so there is nothing to compare")

    records = {r.name: r for r in staged.junit(result["run_dir"])}

    canonical_audio = _tests_needing_audio(
        staged.source(staged.canonical_module))

    assert canonical_audio, (
        "the requirement suite has no audio case, so this proves nothing")

    for name in sorted(canonical_audio):
        record = records[name]

        assert record.status == reporting.SKIPPED, (
            "{} reported a DSP verdict on a board with no loopback: {}".format(
                name, record.message))
        assert "loopback" in (record.message + record.detail).lower(), (
            name, record.message)

    # Nothing anywhere in the run failed, and the verdict is not "fail".
    failures = [r for r in records.values()
                if r.status in (reporting.FAILED, reporting.ERROR)]

    assert not failures, [(r.name, r.message) for r in failures]
    assert result["status"] == "pass", result["status"]

    # One plan, so nothing escalated, and no defect was filed for a feature
    # the firmware never had.
    assert len(staged.plans) == 1, "a missing feature triggered a re-plan"
    assert kpi.load_escapes() == [], kpi.load_escapes()

    # The board-driven cases that need no audio still ran.
    assert records["test_memory"].status == reporting.PASSED
    assert any(r.status == reporting.PASSED for name, r in records.items()
               if name.startswith("test_bat_001")), (
        "the battery requirement case did not run")


# --------------------------------------------------------------------------
# The whole pipeline, with a board whose DSP has stopped working
# --------------------------------------------------------------------------

def test_a_broken_dsp_fails_the_run_escalates_it_and_is_recorded(staged):
    """The verdict has to be able to be "fail", or none of it means anything.

    The board echoes audio back untouched: the link works, the loopback
    works, and the DSP does nothing. That is a regression the generated
    suite exists to catch, so the run must fail, escalate once, re-run, and
    file the failures as defects this run caught.
    """
    staged.device.dsp = "passthrough"

    result = orchestrator.run_pipeline(
        metrics=dict(HEALTHY_METRICS, unmeasured=["power"]),
        change_info="the compressor release constant was retuned",
    )

    records = {r.name: r for r in staged.junit(result["run_dir"])}

    assert records["test_audio_dsp"].status == reporting.FAILED, (
        "a device that echoed the input unchanged passed the DSP test")

    assert result["status"] == "fail"

    # Escalation really happened, and really raised the intensity: the
    # module on disk and the plan the KPI recorded are the escalated ones.
    assert len(staged.plans) == 2, "the failure did not trigger a re-plan"

    first, second = (plan.intensity for plan in staged.plans)

    assert planner.INTENSITIES.index(second) > planner.INTENSITIES.index(
        first), "the escalated plan is no harder than the one that failed"

    assert result["intensity"] == second
    assert 'INTENSITY = "{}"'.format(second) in staged.source(
        staged.planner_module)

    entry = kpi.load_runs()[-1]

    assert entry["status"] == "fail"
    assert entry["failed"] == sum(
        1 for r in records.values()
        if r.status in (reporting.FAILED, reporting.ERROR))
    assert entry["intensity"] == result["intensity"]

    # The failing tests were filed as defects the run caught.
    escapes = kpi.load_escapes()

    assert escapes, "a failing run recorded no defect"
    assert all(e["phase"] == "pre_integration" for e in escapes), escapes


def test_a_loopback_that_stops_replying_fails_the_run(staged):
    """A board that HAS the loopback and stops answering must fail.

    The board here reports the loopback and then notifies nothing back,
    which is what the firmware does when the DSP hangs, a write fails or
    the reply times out -- send_audio_stream returns None for all of them.
    The two silences have opposite verdicts, so the probe decides which one
    this is, and this run must be the failing one.
    """
    staged.device.dsp = "silent"

    result = orchestrator.run_pipeline(
        metrics=dict(HEALTHY_METRICS, unmeasured=["power"]),
        change_info="the compressor release constant was retuned",
    )

    records = {r.name: r for r in staged.junit(result["run_dir"])}

    assert result["status"] == "fail", (
        "a board that reports a loopback and answers nothing was reported "
        "as a passing run")

    # And it is decided from the GATT table, not from an echo. A probe
    # that writes audio and waits for it asks the hung part whether it is
    # there. No write, so nothing the DSP does moves it.
    assert staged.device.client.writes == 0, (
        "the capability probe wrote {} time(s) to a board whose DSP is "
        "hung; a probe the fault can break is not a "
        "capability".format(staged.device.client.writes))
    assert staged.device.client.table_reads > 0, (
        "the GATT table was never read, so the capability was decided "
        "from something else")

    # Nothing anywhere in the run was excused as a missing feature: the
    # probe says the board has it. That skip is the whole bug -- an audio
    # case skipping here is a hung DSP reported as firmware that never had
    # the feature, and a run of them reports pass.
    # The message, not the detail: pytest puts the module's own path in the
    # detail, and this test's tmp_path has "loopback" in its name.
    excused = sorted(r.name for r in records.values()
                     if r.status == reporting.SKIPPED
                     and "loopback" in r.message.lower())

    assert not excused, excused

    # Both modules really exercised the audio and both really failed.
    for module in (staged.planner_module, staged.canonical_module):
        audio = _tests_needing_audio(staged.source(module))

        assert audio, "no audio case in " + module

        failed = sorted(name for name in audio
                        if records[name].status in (reporting.FAILED,
                                                    reporting.ERROR))

        assert failed, "no audio case failed in {}: {}".format(
            module, {name: records[name].status for name in sorted(audio)})

    # A measurement case says what is wrong, rather than blaming a feature
    # the board reports it has.
    measured = [r.name for r in records.values() if "not a gap" in r.message]

    assert measured, "no case reported the silent loopback as a failure"

    # And it was filed as a defect this run caught, like any other failure.
    escapes = kpi.load_escapes()

    assert escapes, "a failing run recorded no defect"
    assert kpi.load_runs()[-1]["status"] == "fail"


def test_a_probe_write_error_is_not_a_missing_feature(staged):
    """A probe that cannot write must not answer "this firmware has none".

    The board publishes the loopback characteristic and its DSP has
    stopped, so every audio case on it is a failure. The capability is
    read from the GATT table, which a failed write cannot change.
    """
    staged.device.probe_write_error = True
    staged.device.dsp = "silent"

    result = orchestrator.run_pipeline(
        metrics=dict(HEALTHY_METRICS, unmeasured=["power"]),
        change_info="the compressor release constant was retuned",
    )

    records = {r.name: r for r in staged.junit(result["run_dir"])}

    assert result["status"] == "fail", (
        "a board whose DSP is dead passed because the capability probe "
        "could not write to it")

    # Nothing was excused as a missing feature: the characteristic is in
    # the table, so this firmware has the loopback whatever the writes did.
    # The message, not the detail: pytest puts the module path in the
    # detail and this test's tmp_path carries the word.
    excused = sorted(r.name for r in records.values()
                     if r.status == reporting.SKIPPED
                     and "loopback" in r.message.lower())

    assert not excused, excused

    # The capability never depends on a write at all, so a write that
    # raises is not an answer about the feature.
    assert staged.device.client.writes == 0, (
        "the capability probe wrote {} time(s), so a write that raises is "
        "still an answer".format(staged.device.client.writes))

    # The silence was reported as a failure, in both generated modules.
    for module in (staged.planner_module, staged.canonical_module):
        audio = _tests_needing_audio(staged.source(module))

        assert audio, "no audio case in " + module

        failed = sorted(name for name in audio
                        if records[name].status in (reporting.FAILED,
                                                    reporting.ERROR))

        assert failed, "no audio case failed in {}: {}".format(
            module, {name: records[name].status for name in sorted(audio)})

    assert kpi.load_escapes(), "a failing run recorded no defect"
    assert kpi.load_runs()[-1]["status"] == "fail"


def test_a_gatt_table_that_cannot_be_read_is_not_an_answer(staged):
    """Unknown is not no.

    The table can fail to read -- the link dropped, discovery has not
    finished. The probe raises, which pytest reports as a failure, and the
    reason names the read rather than the firmware.
    """
    device = staged.device
    loop = asyncio.new_event_loop()

    try:
        loop.run_until_complete(device.connect())

        device.client.table_error = True

        with pytest.raises(ble_audio.LoopbackProbeError) as caught:
            loop.run_until_complete(device.supports_audio_loopback())

        assert "GATT" in str(caught.value), str(caught.value)
        assert device.client.writes == 0

        # Nothing was remembered, so the next probe on a readable link
        # still gets a real answer.
        device.client.table_error = False

        assert loop.run_until_complete(
            device.supports_audio_loopback()) is True
    finally:
        loop.close()

    _reset_event_loop()


def test_a_characteristic_that_cannot_notify_is_not_a_loopback(staged):
    """Published is not the same as usable.

    A board can carry NOTIFY_CHAR_UUID in its table with neither the
    notify nor the indicate property, and then it cannot send processed
    audio back however well its DSP works. That is a firmware gap and
    skips, like an absent characteristic -- the capability is what the
    device can do, not what it has named.
    """
    device = staged.device
    device.notify_properties = ["read", "write"]

    loop = asyncio.new_event_loop()

    try:
        assert loop.run_until_complete(
            device.supports_audio_loopback()) is False
        assert device.client.writes == 0
    finally:
        loop.close()

    _reset_event_loop()


def test_firmware_without_the_characteristic_still_connects(monkeypatch):
    """A characteristic that is not there must not stop the link.

    connect() subscribes to NOTIFY_CHAR_UUID, and bleak raises when the
    device does not publish it. The subscription is optional; the
    capability is read from the GATT table afterwards, and says no.
    """
    class _Advertised:
        name = "Zephyr_Earbuds"
        address = "00:11:22:33:44:55"

    async def found(timeout=None):
        return _Advertised()

    for loopback, failures in ((False, 1), (True, 0)):
        client = _StubBleakClient(loopback=loopback)

        monkeypatch.setattr(ble_audio, "asyncio", _Unpaced())
        monkeypatch.setattr(ble_audio, "find_device", found)
        monkeypatch.setattr(ble_audio, "_bleak",
                            lambda: (lambda handle: client, None))

        device = ble_audio.RealBLEDevice()
        loop = asyncio.new_event_loop()

        try:
            loop.run_until_complete(device.connect())

            assert device.is_connected, (
                "a missing notify characteristic prevented the connection")
            assert client.notify_failures == failures

            assert loop.run_until_complete(
                device.supports_audio_loopback()) is loopback
        finally:
            loop.close()

    _reset_event_loop()


# --------------------------------------------------------------------------
# The document that actually ships
# --------------------------------------------------------------------------

def test_the_shipped_requirements_document_generates_a_suite_that_compiles(
        staged, monkeypatch):
    """The small fixture above keeps the pipeline tests quick; this is the
    real document, through the real generator.

    REQUIREMENTS.md is edited by hand and is the one input here nobody
    validates before a run reads it.
    """
    shipped = os.path.join(paths.APP_DIR, "REQUIREMENTS.md")

    assert os.path.exists(shipped), shipped

    monkeypatch.setenv(orchestrator.REQUIREMENTS_ENV, shipped)
    monkeypatch.delenv(orchestrator.RELEASE_NOTE_ENV, raising=False)

    path = orchestrator.build_canonical_suite()

    assert path == staged.canonical_module

    source = staged.source(path)

    assert _compiles(path, source)
    assert governance.check_file(path) == [], governance.check_file(path)

    names = _test_names(source)

    assert len(names) > 20, "the shipped document yielded {} cases".format(
        len(names))
    assert len(names) == len(set(names)), "two cases share a function name"

    # Every requirement in the document is traceable to at least one case,
    # which is the whole claim the document makes.
    requirements = canonical.read_requirements(shipped)

    assert requirements, "no requirements were parsed from the shipped file"

    missing = [r["id"] for r in requirements if r["id"] not in source]

    assert not missing, "no case traces to {}".format(missing)
